// Rebuilds games/traffic-jam/src/levels.ts: 8 Levels per Chapter, easiest first.
// Usage: npm run traffic-jam:generate -- [seed]
// Same seed, same Levels. Hand edits to levels.ts are fine; levels.test.ts re-checks them.

import { writeFileSync } from 'node:fs';
import { CHAPTERS, LEVELS_PER_CHAPTER } from '../src/chapters';
import type { Level, Street, Vehicle } from '../src/game/level';
import { chapterLevels } from './generator';

const seed = Number(process.argv[2] ?? 1);

const street = (s: Street) =>
  `{ axis: '${s.axis}', at: ${s.at}, lanes: ${s.lanes}${s.from !== undefined ? `, from: ${s.from}` : ''}${s.to !== undefined ? `, to: ${s.to}` : ''} }`;
const vehicle = (v: Vehicle) => `{ kind: '${v.kind}', x: ${v.x}, y: ${v.y}, dir: '${v.dir}', arrow: '${v.arrow}' }`;
const level = (l: Level) =>
  [
    `    {`,
    `      w: ${l.w}, h: ${l.h},`,
    `      streets: [${l.streets.map(street).join(', ')}],`,
    `      vehicles: [`,
    ...l.vehicles.map((v) => `        ${vehicle(v)},`),
    `      ],`,
    `    },`,
  ].join('\n');

const chapters = CHAPTERS.map((spec, i) => {
  const levels = chapterLevels(spec, seed * 1000 + i, LEVELS_PER_CHAPTER);
  console.log(`chapter ${i + 1} (${spec.name}): done`);
  return `  // Chapter ${i + 1}: ${spec.name}\n  [\n${levels.map(level).join('\n')}\n  ],`;
});

const source = `// Generated by \`npm run traffic-jam:generate -- ${seed}\`. Safe to hand-edit: levels.test.ts checks every Level.

import type { Level } from './game/level';

/** Levels by Chapter, easiest first. */
export const LEVELS: readonly (readonly Level[])[] = [
${chapters.join('\n')}
];
`;

writeFileSync(new URL('../src/levels.ts', import.meta.url), source);
