// Rebuilds games/way-out/src/levels.ts and pools.ts.
// Usage: npm run way-out:build -- [seed] [path to rush.txt.gz]
// Needs Michael Fogleman's database: download it once (see the game's README).
// Same seed and database, same Levels. Hand edits are fine; levels.test.ts re-checks them.

import { existsSync, writeFileSync } from 'node:fs';
import { measure } from '../src/game/measure';
import { PACKS, type Level } from '../src/packs';
import { extra, pickLevels, pickPool, type Measured } from './pick';
import { generate, random, readDatabase, type Candidate } from './sources';

const seed = Number(process.argv[2] ?? 1);
const database = process.argv[3] ?? new URL('./rush.txt.gz', import.meta.url).pathname;
const POOL_SIZE = 200;

if (!existsSync(database)) {
  console.error(`No database at ${database}. Download it first:\n  curl -o games/way-out/scripts/rush.txt.gz https://www.michaelfogleman.com/static/rush/rush.txt.gz`);
  process.exit(1);
}

const rand = random(seed);

console.log('generating easy boards...');
// Pack 1 comes only from the generator; Pack 2 mixes it with the database.
const generated = generate(seed, 6000, PACKS[1]!.vehicles[1], PACKS[1]!.par[1]);

console.log('reading the database...');
const fromDatabase = [[], ...(await readDatabase(database, PACKS.slice(1), 150, seed))];

const measured = (list: Candidate[]): Measured[] => list.map((c) => ({ ...c, m: measure(c.board) }));

const levels: Level[] = [];
const pools: Measured[][] = [];
const taken = new Set<string>();

PACKS.forEach((spec, i) => {
  const pack = i + 1;
  const pool = new Map<string, Candidate>();
  for (const c of [...(i < 2 ? generated : []), ...fromDatabase[i]!]) if (!taken.has(c.board)) pool.set(c.board, c);
  // Par 1 means nothing is in the way: not a puzzle.
  const candidates = measured([...pool.values()]).filter((c) => c.m.par >= 2);
  console.log(`pack ${pack} (${spec.name}): ${candidates.length} candidates`);

  // Level 1 is one car in the way.
  const picked = pickLevels(spec, PACKS[i - 1], candidates, rand, pack === 1 ? { par: 2, vehicles: 2 } : undefined);
  picked.forEach((c, n) => {
    taken.add(c.board);
    levels.push({ id: `p${pack}-${String(n + 1).padStart(2, '0')}`, pack, index: n + 1, board: c.board, par: c.par, source: c.source });
  });
  const extras = pickPool(spec, candidates, taken, POOL_SIZE, rand);
  for (const c of extras) taken.add(c.board);
  pools.push(extras);
  console.log(`  levels: ${picked.map((c) => `${c.m.par}/${c.m.vehicles}/${extra(c.m)}`).join(' ')}; pool ${extras.length}`);
});

const levelLine = (l: Level) =>
  `  { id: '${l.id}', pack: ${l.pack}, index: ${l.index}, board: '${l.board}', par: ${l.par}, source: '${l.source}' },`;

writeFileSync(
  new URL('../src/levels.ts', import.meta.url),
  `// Generated by \`npm run way-out:build -- ${seed}\`. Safe to hand-edit: levels.test.ts checks every Level.

import type { Level } from './packs';

/** Every Level, Pack by Pack, easiest first. */
export const LEVELS: readonly Level[] = [
${levels.map(levelLine).join('\n')}
];
`,
);

writeFileSync(
  new URL('../src/pools.ts', import.meta.url),
  `// Generated by \`npm run way-out:build -- ${seed}\`. Extra puzzles for "more like this", one Pool per Pack.
// Loaded only when a child asks for one. levels.test.ts checks every board and par.

import type { PoolPuzzle } from './packs';

export const POOLS: readonly (readonly PoolPuzzle[])[] = [
${pools.map((pool, i) => `  // Pack ${i + 1}: ${PACKS[i]!.name}\n  [\n${pool.map((c) => `    ['${c.board}', ${c.par}],`).join('\n')}\n  ],`).join('\n')}
];
`,
);

console.log(`wrote ${levels.length} Levels and ${pools.flat().length} Pool puzzles`);
